// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCJtABJZodbUTKXI3OQHY4YmkWXNV7ZU',
    appId: '1:889265575922:web:e20a2fda665ebf8129fd6b',
    messagingSenderId: '889265575922',
    projectId: 'fir-learning-github',
    authDomain: 'fir-learning-github.firebaseapp.com',
    storageBucket: 'fir-learning-github.appspot.com',
    measurementId: 'G-EG6L2VMFC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw443sKQ1nuLw4rDCu1Y-sI9Ibpymbnaw',
    appId: '1:889265575922:android:75c65ffceeee645d29fd6b',
    messagingSenderId: '889265575922',
    projectId: 'fir-learning-github',
    storageBucket: 'fir-learning-github.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yiHN-Z1BSOoy7Vn40q6xLhbGF55yrRU',
    appId: '1:889265575922:ios:3d06937599e6fa7329fd6b',
    messagingSenderId: '889265575922',
    projectId: 'fir-learning-github',
    storageBucket: 'fir-learning-github.appspot.com',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_yiHN-Z1BSOoy7Vn40q6xLhbGF55yrRU',
    appId: '1:889265575922:ios:3d06937599e6fa7329fd6b',
    messagingSenderId: '889265575922',
    projectId: 'fir-learning-github',
    storageBucket: 'fir-learning-github.appspot.com',
    iosBundleId: 'com.example.firebaseLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCJtABJZodbUTKXI3OQHY4YmkWXNV7ZU',
    appId: '1:889265575922:web:c299963fa320528529fd6b',
    messagingSenderId: '889265575922',
    projectId: 'fir-learning-github',
    authDomain: 'fir-learning-github.firebaseapp.com',
    storageBucket: 'fir-learning-github.appspot.com',
    measurementId: 'G-NJD53LMFY0',
  );
}
